[issue-467] Improve the readme doc with more development guide
pravega/flink-connectors pull request #469
Opened 2021-03-12 07:57 UTC by fyang86

Signed-off-by: Fan, Yang <fan.yang5@emc.com>

**Change log description**
Add a new dev guide to improve the document to let contributors more clear to how the connector build and work.

**Purpose of the change**
Fix #467 

**What the code does**
Add a new dev guide

**How to verify it**
`./gradlew clean build` passes

2021-03-12 10:07 UTC, crazyzhou requested changes

2021-03-12 10:07 UTC, crazyzhou commented on documentation/src/docs/dev-guide.md
> +        .flatMap(new WordCountReader.Splitter())
```suggestion
        .flatMap(new Tokenizer())  // The Tokenizer() splits the line into words, and emit streams of "WordCount(word, 1)"
```

2021-03-17 03:07 UTC, crazyzhou requested changes

2021-03-17 03:07 UTC, crazyzhou commented on documentation/src/docs/dev-guide.md
> +Use gradle or maven to assemble a distribution folder containing the Flink programs as a ready-to-deploy fat-jar
This requires the assemble plugin in gradle which is not generic, we can just say use the packaged jar, and run 
```
flink run -c <classname> ${your-app}.jar --controller <pravega-controller-uri>
```
We don't need to specify below things like creating socket connection or checking the output, these things will be covered in the dev guide for samples.

2021-03-17 03:09 UTC, derekm commented on documentation/src/docs/dev-guide.md
> +To complete this guide, you need:
newline required between this line and the first bullet in order for bullet points to render propertly in MkDocs

2021-03-17 03:10 UTC, derekm commented
See this file here: https://pravega.io/docs/nightly/flink-connectors/documentation/src/docs/dev-guide/

2021-03-17 03:10 UTC, crazyzhou requested changes

2021-03-17 03:10 UTC, crazyzhou commented on documentation/src/docs/dev-guide.md
> +
We may add an extra section or just some words here talking about `Run and Debug in local IDE`, this may help for local application development.

2021-03-17 03:10 UTC, crazyzhou commented on documentation/src/docs/dev-guide.md
> +flinkShadowJar group: 'org.apache.flink', name: 'flink-streaming-java_2.12', version: '1.11.2'
This should not be part of flinkshadowjar, please check the Flink doc.

2021-03-19 14:19 UTC, crazyzhou approved these changes
LGTM

2021-03-19 14:19 UTC, merged