[Issue-512] Add Json support for deserialization in Parvega schema registry format factory
pravega/flink-connectors pull request #515
Opened 2021-05-20 09:12 UTC by fyang86

**Change log description**
In #424  we have implement format factory to support serialization/deserialization in schema registry but only with Avro format. 
Add Json support for deserialization in Pravega Schema Registry format factory.

**Purpose of the change**
Fix #512 

**What the code does**
Add Json support in `PravegaRegistryRowDataDeserializationSchema`
Implement `open()` method in `PravegaRegistryRowDataDeserializationSchema` and `PravegaRegistryRowDataSerializationSchema`
Add Json related options in `PravegaRegistryOptions`

**How to verify it**
`./gradlew clean build` passes

2021-06-09 08:01 UTC, crazyzhou requested changes

2021-06-10 07:16 UTC, fyang86 commented on src/main/java/io/pravega/connectors/flink/formats/registry/PravegaRegistryRowDataDeserializationSchema.java
> +        SchemaRegistryClient schemaRegistryClient = SchemaRegistryClientFactory.withNamespace(namespace,
This client needs to be passed to the class constructor of `FlinkJsonGenericDeserializer`, thus cannot be closed here.

2021-06-15 09:54 UTC, crazyzhou commented on src/main/java/io/pravega/connectors/flink/formats/registry/PravegaRegistryRowDataDeserializationSchema.java
> +        SchemaRegistryClient schemaRegistryClient = SchemaRegistryClientFactory.withNamespace(namespace,
OK.

2021-06-15 09:56 UTC, crazyzhou approved these changes
LGTM

2021-06-15 09:57 UTC, merged