[issue-577] Add support for security in PravegaCatalog
pravega/flink-connectors pull request #578
Opened 2021-09-06 08:14 UTC by fyang86

Signed-off-by: Fan, Yang <fan.yang5@emc.com>

**Change log description**
- use `ClientConfig` to create `StreamManager` instead of `ControllerURI` when creating `PravegaCatalog` in order to set security configs which can be read from `ClientConfig`
- enable `enableTls`

**Purpose of the change**
Fix #577 

**What the code does**
Add Pravega security options in Catalog factory options so that we can create `StreamManager` upon `ClientConfig` that contains security configs.
Set `enableTls` to true for integration tests.

**How to verify it**
`./gradlew clean build` passed

2021-09-10 07:12 UTC, crazyzhou requested changes

2021-09-10 09:24 UTC, crazyzhou requested changes

2021-09-10 09:24 UTC, crazyzhou commented on src/main/java/io/pravega/connectors/flink/table/catalog/pravega/factories/PravegaCatalogFactory.java
>          SchemaRegistryClientConfig schemaRegistryClientConfig = SchemaRegistryClientConfig.builder().
This should use `SchemaRegistryUtils.getSchemaRegistryClientConfig` method to construct, otherwise credential information is not included.

2021-09-10 09:24 UTC, crazyzhou commented on src/test/java/io/pravega/connectors/flink/formats/registry/PravegaRegistrySeDeITCase.java
> +        properties.put(FactoryUtil.CONNECTOR.key(), FlinkPravegaDynamicTableFactory.IDENTIFIER);
Here is the same, using plain string would be better.

2021-09-10 09:24 UTC, crazyzhou commented on src/main/java/io/pravega/connectors/flink/table/catalog/pravega/factories/PravegaCatalogFactory.java
> + * <p>
Is this change accidental? It looks not related

2021-09-10 09:24 UTC, crazyzhou commented on src/main/java/io/pravega/connectors/flink/table/catalog/pravega/PravegaCatalog.java
>  public class PravegaCatalog extends AbstractCatalog {
We should add more java docs on both the class and the variables below.

2021-09-14 09:13 UTC, crazyzhou requested changes

2021-09-14 09:13 UTC, crazyzhou commented on src/main/java/io/pravega/connectors/flink/table/catalog/pravega/PravegaCatalog.java
> +        this.serializationFormat = serializationFormat;
I prefer the previous way, pass the string there and change it to `SerializationFormat` here.

2021-09-14 09:13 UTC, crazyzhou commented on src/main/java/io/pravega/connectors/flink/table/catalog/pravega/PravegaCatalog.java
> +     * @param properties              The options read from configuration.
```suggestion
     * @param properties              The table options that should propagate from the catalog options.
```

2021-09-14 10:25 UTC, fyang86 commented on src/main/java/io/pravega/connectors/flink/table/catalog/pravega/PravegaCatalog.java
> +                          ClientConfig clientConfig, SchemaRegistryClientConfig config,
agreed, this makes it simpler in the factory

2021-09-15 03:18 UTC, crazyzhou approved these changes
LGTM

2021-09-15 03:18 UTC, merged