updage connector options doc for table-api
pravega/flink-connectors pull request #631
Opened 2021-12-21 07:48 UTC by hehuiyuan

**Change log description**
Update doc for connector options.
Add scope option and scan.reader-group.name option

2021-12-27 07:50 UTC, crazyzhou requested changes
Thanks for your contribution, I have created issue #634 for this and please use this as the PR title and sign-off your commit.

2021-12-27 07:50 UTC, crazyzhou commented on documentation/src/docs/table-api.md
> +| scan.reader-group.name                                 | required for source | (none)        | String       | Pravega reader group name
This is changed to optional by #493 which is addressed in 0.9.1 release notes.

2021-12-27 07:51 UTC, hehuiyuan commented
亲，发的东西收到了！

2022-01-14 08:08 UTC, hehuiyuan commented
亲，发的东西收到了！

2022-02-11 03:04 UTC, crazyzhou commented
As there is no valid response for a long time, we will close this PR

2022-02-11 03:04 UTC, closed without merging

2022-02-11 03:04 UTC, hehuiyuan commented
亲，发的东西收到了！

2022-02-11 14:01 UTC, hehuiyuan commented
> As there is no valid response for a long time, we will close this PR

Sorry for the delay